server:
  port: ${HOST_PORT}

spring:
  sql:
    init:
      mode: always

  datasource:
    url: jdbc:mysql://${DB_HOST}:3306/traffic?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: administrator
    password: administrator

  jpa:
    show-sql: true
